Helps if you touch the right file

diff --git a/.github/workflows/test_branches.yml b/.github/workflows/test_branches.yml
--- a/.github/workflows/test_branches.yml
+++ b/.github/workflows/test_branches.yml
@@ -377,7 +377,48 @@ jobs:
             else
                 XPRESS='xpress'
             fi
-            conda install -q -y 'cplex>=12.10' docplex gurobi "$XPRESS" cyipopt pymumps scip
+            PYVER=$(echo "py${{matrix.python}}" | sed 's/\.//g')
+            echo "Installing for $PYVER"
+            for PKG in 'cplex>=12.10' docplex gurobi "$XPRESS" cyipopt pymumps scip; do
+                echo ""
+                echo "*** Install $PKG ***"
+                echo ""
+                # conda can literally take an hour to determine that a
+                # package is not available.  Perform a quick search to see
+                # if the package is available for this interpreter before
+                # attempting an install.
+                # NOTE: conda search will attempt approximate matches.
+                _PKGLIST=$(conda search -f "$PKG") || echo "Package $PKG not found"
+                echo "$_PKGLIST"
+                _BASE=$(echo "$PKG" | sed 's/[=<>].*//')
+                _BUILDS=$(echo "$_PKGLIST" | grep "^$_BASE " \
+                    | sed -r 's/\s+/ /g' | cut -d\  -f3) || echo ""
+                if test -n "$_BUILDS"; then
+                    _ISPY=$(echo "$_BUILDS" | grep "^py") \
+                        || echo "INFO: No python build detected."
+                    _PYOK=$(echo "$_BUILDS" | grep -E "^($PYVER|pyh)") \
+                        || echo "INFO: No python build matching $PYVER detected."
+                    if test -z "$_ISPY" -o -n "$_PYOK"; then
+                        echo ""
+                        echo "... INSTALLING $PKG"
+                        # Because conda can occasionally hang
+                        # indefinitely (lately while installing SCIP),
+                        # we will run "conda install" in a subshell and
+                        # kill it after 5-minutes.
+                        (conda install -q -y $PKG) &
+                        conda_pid=$!
+                        (sleep 30 && kill -INT "$conda_pid" 2>/dev/null) &
+                        timeout_pid=$!
+                        wait "$conda_pid" || _BUILDS=""
+                        kill "$timeout_pid" 2>/dev/null \
+                            || echo "TIMEOUT: killed conda install process"
+                    fi
+                fi
+                echo ""
+                if test -z "$_BUILDS"; then
+                    echo "WARNING: $PKG is not available"
+                fi
+            done
         fi
         # Re-try Pyomo (optional) dependencies with pip
         echo ""
@@ -404,6 +445,7 @@ jobs:
         echo ""
         echo "Final conda environment:"
         conda list | sed 's/^/    /'
+
 
     - name: Setup TPL package directories
       run: |
