Print lots of path / IPOPT info and turn off everything else

diff --git a/.github/workflows/test_branches.yml b/.github/workflows/test_branches.yml
--- a/.github/workflows/test_branches.yml
+++ b/.github/workflows/test_branches.yml
@@ -216,6 +216,7 @@ jobs:
       run: |
         echo "SETUPTOOLS_USE_DISTUTILS=local" >> $GITHUB_ENV
         choco install pkgconfiglite
+        echo "$PATH"
 
     - name: Set up Python ${{ matrix.python }}
       if: matrix.PYENV == 'pip'
@@ -419,6 +420,8 @@ jobs:
         echo ""
         echo "Final conda environment:"
         conda list | sed 's/^/    /'
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     - name: Setup TPL package directories
       run: |
@@ -463,6 +466,8 @@ jobs:
         echo ""
         echo "$IPOPT_DIR"
         ls -l $IPOPT_DIR
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     - name: Install GAMS
       if: ${{ ! matrix.slim }}
@@ -507,6 +512,8 @@ jobs:
         echo ""
         echo "$GAMS_DIR"
         ls -l $GAMS_DIR
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     - name: Install GAMS Python bindings
       if: ${{ ! matrix.slim }}
@@ -520,6 +527,8 @@ jobs:
             $PYTHON_EXE setup.py install
             popd
         fi
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     - name: Install BARON
       if: ${{ ! matrix.slim }}
@@ -556,6 +565,8 @@ jobs:
         echo ""
         echo "$BARON_DIR"
         ls -l $BARON_DIR
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     - name: Install GJH_ASL_JSON
       if: ${{ ! matrix.slim && matrix.TARGET != 'win' }}
@@ -580,6 +591,8 @@ jobs:
         echo ""
         echo "$GJH_DIR"
         ls -l $GJH_DIR
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     - name: Install Pyomo
       run: |
@@ -595,6 +608,8 @@ jobs:
         echo "Set custom PYOMO_CONFIG_DIR"
         echo ""
         echo "PYOMO_CONFIG_DIR=${GITHUB_WORKSPACE}/config" >> $GITHUB_ENV
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     # this has to be done after Pyomo is installed because highspy 
     # depends on pyomo's find_library function
@@ -604,24 +619,8 @@ jobs:
       run: |
         $PYTHON_EXE -m pip install --cache-dir cache/pip highspy \
             || echo "WARNING: highspy is not available"
-
-    - name: Set up coverage tracking
-      run: |
-        if test "${{matrix.TARGET}}" == win; then
-            COVERAGE_BASE=${GITHUB_WORKSPACE}\\.cover
-        else
-            COVERAGE_BASE=${GITHUB_WORKSPACE}/.cover
-        fi
-        COVERAGE_RC=${COVERAGE_BASE}_rc
-        echo "COVERAGE_RCFILE=$COVERAGE_RC" >> $GITHUB_ENV
-        echo "COVERAGE_PROCESS_START=$COVERAGE_RC" >> $GITHUB_ENV
-        cp ${GITHUB_WORKSPACE}/.coveragerc ${COVERAGE_RC}
-        echo "data_file=${COVERAGE_BASE}age" >> ${COVERAGE_RC}
-        SITE_PACKAGES=$($PYTHON_EXE -c \
-            "import sysconfig; print(sysconfig.get_path('purelib'))")
-        echo "Python site-packages: $SITE_PACKAGES"
-        echo 'import coverage; coverage.process_startup()' \
-            > ${SITE_PACKAGES}/run_coverage_at_startup.pth
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     - name: Download and install extensions
       if: ${{ ! matrix.slim }}
@@ -634,6 +633,8 @@ jobs:
         echo "Pyomo build-extensions"
         echo ""
         pyomo build-extensions --parallel 2
+        echo "$PATH"
+        ipopt --version || echo "IPOPT not found on PATH"
 
     - name: Report pyomo plugin information
       run: |
@@ -641,239 +642,3 @@ jobs:
         pyomo help --solvers || exit 1
         pyomo help --transformations || exit 1
         pyomo help --writers || exit 1
-
-    - name: Run Pyomo tests
-      if: matrix.mpi == 0
-      run: |
-        $PYTHON_EXE -m pytest -v \
-            -W ignore::Warning ${{matrix.category}} \
-            pyomo `pwd`/pyomo-model-libraries \
-            `pwd`/examples `pwd`/doc --junitxml="TEST-pyomo.xml"
-
-    - name: Run Pyomo MPI tests
-      if: matrix.mpi != 0
-      run: |
-        # Manually invoke the DAT parser so that parse_table_datacmds.py
-        # is fully generated by a single process before invoking MPI
-        $PYTHON_EXE -c "from pyomo.dataportal.parse_datacmds import \
-            parse_data_commands; parse_data_commands(data='')"
-        # Note: if we are testing with openmpi, add '--oversubscribe'
-        mpirun -np ${{matrix.mpi}} -oversubscribe pytest -v \
-            --junit-xml=TEST-pyomo-mpi.xml \
-            -m "mpi" -W ignore::Warning \
-            pyomo `pwd`/pyomo-model-libraries
-
-    - name: Run documentation tests
-      if: matrix.skip_doctest == 0
-      run: |
-        make -C doc/OnlineDocs doctest -d
-
-    - name: Process code coverage report
-      run: |
-        coverage combine
-        coverage report -i
-        coverage xml -i
-
-    - name: Record build artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{github.job}}_${{env.GHA_JOBGROUP}}-${{env.GHA_JOBNAME}}
-        path: |
-          .coverage
-          coverage.xml
-          # In general, do not record test results as artifacts to
-          #   manage total artifact storage
-          # TEST-*.xml
-
-
-  bare-python-env:
-    name: linux/3.9/bare-env
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
-    steps:
-    - name: Checkout Pyomo source
-      uses: actions/checkout@v4
-
-    - name: Set up Python 3.9
-      uses: actions/setup-python@v5
-      with:
-        python-version: 3.9
-
-    - name: Install Pyomo
-      run: |
-        echo ""
-        echo "Install Pyomo..."
-        echo ""
-        python setup.py develop
-        echo ""
-        echo "Set custom PYOMO_CONFIG_DIR"
-        echo ""
-        echo "PYOMO_CONFIG_DIR=${GITHUB_WORKSPACE}/config" >> $GITHUB_ENV
-
-    - name: Report pyomo plugin information
-      run: |
-        echo "$PATH"
-        pyomo help --solvers || exit 1
-        pyomo help --transformations || exit 1
-        pyomo help --writers || exit 1
-
-    - name: Run Pyomo standalone test
-      run: |
-        echo ""
-        echo "Running standalone Pyomo test"
-        echo ""
-        python `pwd`/pyomo/environ/tests/standalone_minimal_pyomo_driver.py \
-            || exit 1
-
-
-  cover:
-    name: process-coverage-${{ matrix.TARGET }}
-    needs: build
-    if: ${{ false }} # turn off for branches
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 10
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest, macos-13, windows-latest]
-
-        include:
-        - os: ubuntu-latest
-          TARGET: linux
-        - os: macos-13
-          TARGET: osx
-        - os: windows-latest
-          TARGET: win
-
-    steps:
-    - name: Checkout Pyomo source
-      uses: actions/checkout@v4
-      # We need the source for .codecov.yml and running "coverage xml"
-
-    #- name: Pip package cache
-    #  uses: actions/cache@v4
-    #  id: pip-cache
-    #  with:
-    #    path: cache/pip
-    #    key: pip-${{env.CACHE_VER}}.0-${{runner.os}}-3.9
-
-    - name: Download build artifacts
-      uses: actions/download-artifact@v4
-      with:
-        path: artifacts
-
-    - name: Set up Python 3.9
-      uses: actions/setup-python@v5
-      with:
-        python-version: 3.9
-
-    - name: Install Python Packages (pip)
-      shell: bash # DO NOT REMOVE: see note above
-      run: |
-        python -c 'import sys;print(sys.executable)'
-        python -m pip install --cache-dir cache/pip --upgrade pip
-        PYOMO_DEPENDENCIES=`python setup.py dependencies \
-            --extras "tests" | tail -1`
-        python -m pip install --cache-dir cache/pip \
-            ${PYTHON_CORE_PKGS} ${PYOMO_DEPENDENCIES}
-        python -c 'import sys; print("PYTHON_EXE=%s" \
-            % (sys.executable,))' >> $GITHUB_ENV
-
-    - name: Install Pyomo
-      run: |
-        echo ""
-        echo "Clone Pyomo-model-libraries..."
-        git clone https://github.com/Pyomo/pyomo-model-libraries.git
-        echo ""
-        echo "Install Pyomo..."
-        echo ""
-        $PYTHON_EXE setup.py develop ${{matrix.setup_options}}
-        echo ""
-        echo "Set custom PYOMO_CONFIG_DIR"
-        echo ""
-        echo "PYOMO_CONFIG_DIR=${GITHUB_WORKSPACE}/config" >> $GITHUB_ENV
-
-    - name: Generate parse_table_datacmds
-      run: |
-        # Manually invoke the DAT parser so that parse_table_datacmds.py
-        # is generated before running "coverage xml"
-        $PYTHON_EXE -c "from pyomo.dataportal.parse_datacmds import \
-            parse_data_commands; parse_data_commands(data='')"
-
-    - name: Update codecov uploader
-      run: |
-        set +e
-        CODECOV="${GITHUB_WORKSPACE}/codecov.sh"
-        echo "CODECOV=$CODECOV" >> $GITHUB_ENV
-        for i in `seq 3`; do
-            echo "Downloading current codecov script (attempt ${i})"
-            curl -L https://codecov.io/bash -o $CODECOV
-            if test $? == 0; then
-                break
-            fi
-            DELAY=$(( RANDOM % 30 + 30))
-            echo "Pausing $DELAY seconds before re-attempting download"
-            sleep $DELAY
-        done
-        if test ! -e $CODECOV; then
-            echo "Failed to download codecov.sh"
-            exit 1
-        fi
-
-    - name: Combine coverage reports
-      if: github.repository_owner == 'Pyomo' || github.ref != 'refs/heads/main'
-      run: |
-        set +e
-        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
-            SHA=$(jq --raw-output .pull_request.head.sha "$GITHUB_EVENT_PATH")
-        else
-            SHA=$GITHUB_SHA
-        fi
-        for ARTIFACT in artifacts/*_*${{matrix.TARGET}}_*; do
-            NAME=`echo $ARTIFACT | cut -d/ -f2`
-            cp -v $ARTIFACT/.coverage .coverage-$NAME
-        done
-        rm -vf .coverage coverage.xml
-        echo "Build: ${{ matrix.TARGET }}/other"
-        echo ""
-        FILES=.coverage-*_other-*
-        coverage combine --debug=dataio $FILES
-        if test ! -e .coverage; then
-            echo "No coverage to upload."
-        else
-            coverage xml || coverage xml -i
-            mv -v coverage.xml coverage-other.xml
-        fi
-        echo ""
-        echo "Build: ${{ matrix.TARGET }}"
-        echo ""
-        FILES=.coverage-*_${{matrix.TARGET}}-*
-        coverage combine --debug=dataio $FILES
-        rm -vf artifacts/*/*.xml
-        if test ! -e .coverage; then
-            echo "No coverage to upload."
-        else
-            coverage xml || coverage xml -i
-        fi
-
-    - name: Upload codecov reports
-      if: github.repository_owner == 'Pyomo' || github.ref != 'refs/heads/main'
-      uses: codecov/codecov-action@v4
-      with:
-        files: coverage.xml
-        token: ${{ secrets.PYOMO_CODECOV_TOKEN }}
-        name: ${{ matrix.TARGET }}
-        flags: ${{ matrix.TARGET }}
-        fail_ci_if_error: true
-
-    - name: Upload other coverage reports
-      if: |
-        hashFiles('coverage-other.xml') != '' &&
-        (github.repository_owner == 'Pyomo' || github.ref != 'refs/heads/main')
-      uses: codecov/codecov-action@v4
-      with:
-        files: coverage-other.xml
-        token: ${{ secrets.PYOMO_CODECOV_TOKEN }}
-        name: ${{ matrix.TARGET }}/other
-        flags: ${{ matrix.TARGET }},other
-        fail_ci_if_error: true
